name: Build Runner

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    # FIXME: https://github.com/actions/virtual-environments/issues/5490#issuecomment-1118328567
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: |
          make build
