name: Build Runner

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  build:
    # FIXME: https://github.com/actions/virtual-environments/issues/5490#issuecomment-1118328567
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/export-runtime

      - name: Build Image
        run: |
          docker buildx create --name builder --use --driver docker-container
          make build BUILDX_ARGS="--cache-from=type=gha --cache-to=type=gha,mode=max --load"

      - name: Push Image
        if: ${{ github.event_name == 'push' }}
        run: |-
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          test "$GITHUB_REF_NAME" = master && \
            make push TAG=latest || \
            make push TAG="$GITHUB_REF_NAME"
