name: Build Runner

on:
  push:
    branches: [master, dev]
    paths:
      - 'linux/**'
  pull_request:
    branches: [master]
    paths:
      - 'linux/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/export-runtime

      - name: Build Image
        run: |
          docker buildx create --name builder --use --driver docker-container
          make -C linux build BUILDX_ARGS="--cache-from=type=gha --cache-to=type=gha,mode=max --load"

      - name: Push Image
        if: ${{ github.event_name == 'push' }}
        run: |-
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          test "$GITHUB_REF_NAME" = master && \
            make -C linux push TAG=latest || \
            make -C linux push TAG="$GITHUB_REF_NAME"
